# This file is part of lutter, a simple ray tracer
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import glob
from os import path

Import('env', 'buildroot', 'project')
localenv = env.Clone()

builddir = path.join(buildroot, project)
targetpath = path.join(builddir, "liblutter.a")

localenv.Append(CPPPATH=['../../Lunch-Time-Tracer/Include',
                         '../include/lutter'])

localenv.VariantDir(builddir, ".", duplicate=0)

srclst = map(lambda x: builddir + '/' + x, glob.glob('*.cpp'))
localenv.Library(targetpath, source=srclst)
