# This file is part of lutter, a simple ray tracer
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from os import path
import glob

Import('env', 'buildroot', 'project')
localenv = env.Clone()

builddir = path.join(buildroot, project)
targetpath = path.join(builddir, project)

localenv.Append(LIBS = 'lutter', LIBPATH = [path.join(buildroot, 'lib')])
localenv.Append(CPPPATH=['../include'])

localenv.VariantDir(builddir, ".", duplicate=0)

srclst = map(lambda x: builddir + '/' + x, glob.glob('*.cpp'))
localenv.Program(targetpath, source=srclst)
